from django.db import models

# Create your models here.

class NotifyOrderModel(models.Model):
    return_code=models.CharField(max_length=16)
    return_msg=models.CharField(max_length=128,default='',blank=True)
    appid=models.CharField(max_length=32,default='',blank=True)
    mch_id=models.CharField(max_length=32,default='',blank=True)
    device_info=models.CharField(max_length=32,default='',blank=True)
    nonce_str=models.CharField(max_length=32,default='',blank=True)
    sign=models.CharField(max_length=32,default='',blank=True)
    sign_type=models.CharField(max_length=32,default='',blank=True)
    result_code=models.CharField(max_length=16,default='',blank=True)
    err_code=models.CharField(max_length=32,default='',blank=True)
    err_code_des=models.CharField(max_length=128,default='',blank=True)
    openid=models.CharField(max_length=128,default='',blank=True)
    is_subscribe=models.CharField(max_length=1,default='',blank=True)
    trade_type=models.CharField(max_length=16,default='',blank=True)
    bank_type=models.CharField(max_length=16,default='',blank=True)
    total_fee=models.IntegerField(default=0,blank=True)
    settlement_total_fee =models.IntegerField(default=0,blank=True)
    fee_type=models.CharField(max_length=8,default='',blank=True)
    cash_fee=models.IntegerField(default=0,blank=True)
    cash_fee_type=models.CharField(max_length=16,default='',blank=True)
    coupon_fee=models.IntegerField(default=0,blank=True)
    coupon_count=models.IntegerField(default=0,blank=True)
    coupon_type_0=models.CharField(max_length=8,default='',blank=True)
    coupon_id_0=models.CharField(max_length=20,default='',blank=True)
    coupon_fee_0=models.IntegerField(default=0,blank=True)
    transaction_id=models.CharField(max_length=32,default='',blank=True)
    out_trade_no=models.CharField(max_length=32,default='',blank=True)
    attach=models.CharField(max_length=128,default='',blank=True)
    time_end=models.CharField(max_length=14,default='',blank=True)
