# Generated by Django 2.0.5 on 2018-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(editable=False, help_text='用户小程序ID', max_length=50, primary_key=True, serialize=False)),
                ('openId', models.CharField(default='', help_text='用户公开ID', max_length=100)),
                ('avatarUrl', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('gender', models.SmallIntegerField(default=1)),
                ('language', models.CharField(default='', max_length=50)),
                ('nickName', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
