# Generated by Django 2.0.5 on 2018-06-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(editable=False, help_text='用户小程序ID', max_length=50, primary_key=True, serialize=False)),
                ('openId', models.CharField(default='', help_text='用户公开ID', max_length=100)),
                ('avatarUrl', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('gender', models.SmallIntegerField(default=1)),
                ('language', models.CharField(default='', max_length=50)),
                ('nickName', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudioStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplingRate', models.IntegerField(default=44100)),
                ('bitrate', models.IntegerField(default=128498)),
                ('codec', models.CharField(blank=True, default='aac', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='sjmeigou/%Y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrate', models.IntegerField(default=788426)),
                ('height', models.IntegerField(default=360)),
                ('width', models.IntegerField(default=640)),
                ('codec', models.CharField(blank=True, default='mpeg4', max_length=30)),
                ('fps', models.IntegerField(default=23)),
            ],
        ),
        migrations.CreateModel(
            name='VodCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', max_length=10)),
                ('eventType', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('vodTaskId', models.CharField(blank=True, default='', max_length=100)),
                ('fileId', models.CharField(blank=True, default='', max_length=50)),
                ('fileUrl', models.CharField(blank=True, default='', max_length=255)),
                ('continued', models.IntegerField(default=0)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('streamId', models.CharField(blank=True, default='', max_length=100)),
                ('sourceType', models.CharField(blank=True, default='', max_length=100)),
                ('sourceContext', models.CharField(blank=True, default='', max_length=100)),
                ('callback', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data', to='register.VodCallback')),
            ],
        ),
        migrations.CreateModel(
            name='VodMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=360)),
                ('width', models.IntegerField(default=540)),
                ('bitrate', models.IntegerField(default=916924)),
                ('size', models.IntegerField(default=0)),
                ('container', models.CharField(blank=True, default='mov,mp4,m4a,3gp,3g2,mj2', max_length=50)),
                ('md5', models.CharField(blank=True, default='', max_length=30)),
                ('duration', models.IntegerField(default=0)),
                ('floatDuration', models.FloatField(default=0.0)),
                ('totalSize', models.IntegerField(default=0)),
                ('rotate', models.IntegerField(default=0)),
                ('vodData', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='metaData', to='register.VodData')),
            ],
        ),
        migrations.AddField(
            model_name='videostream',
            name='metaData',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videoStreamList', to='register.VodMetaData'),
        ),
        migrations.AddField(
            model_name='audiostream',
            name='metaData',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audioStreamList', to='register.VodMetaData'),
        ),
    ]
